import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";
// import { getMe } from "@/service/getMe";


const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "FixItNow Home Service",
  description: "Generated by create Shahadat",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const user = await getMe();

  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", roboto.variable)}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        
        <Toaster position="top-right" richColors />
        <Providers>
          {children}
        </Providers>
        {/* Footer */}
      </body>
    </html>
  );
}