import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FixItNow Home Service",
  description: "Generated by create Shahadat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        {/* Navbar */}
        {children}
        {/* Footer */}
      </body>
    </html>
  );
}
